# Generated by Django 5.2.8 on 2025-12-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appdepartamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del municipio o corregimiento.', max_length=150, unique=True, verbose_name='Nombre del Municipio / Corregimiento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
                ('departamento', models.ForeignKey(help_text='Seleccione.', on_delete=django.db.models.deletion.PROTECT, to='appdepartamento.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio / Corregimiento',
                'verbose_name_plural': 'Municipios / Corregimientos',
            },
        ),
    ]
