# Generated by Django 5.2.8 on 2025-12-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
    ]
