# Generated by Django 5.2.8 on 2025-11-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del municipio o corregimiento.', max_length=150, unique=True, verbose_name='Nombre del Municipio / Corregimiento'),
        ),
    ]
