# Generated by Django 5.2.8 on 2025-12-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0002_alter_municipio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del municipio o corregimiento.', max_length=150, unique=True, verbose_name='Nombre del Municipio'),
        ),
    ]
