# Generated by Django 5.2.8 on 2025-12-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppPuestoVotacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Ingrese el número de la mesa.', verbose_name='Número')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
                ('puesto_votacion', models.ForeignKey(help_text='Seleccione el puesto de votación correspondiente.', on_delete=django.db.models.deletion.PROTECT, to='AppPuestoVotacion.puestovotacion', verbose_name='Puesto de Votación')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'constraints': [models.UniqueConstraint(fields=('numero', 'puesto_votacion'), name='unique_mesa_por_puesto')],
            },
        ),
    ]
