# Generated by Django 5.2.8 on 2025-11-28 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPuestoVotacion', '0001_initial'),
        ('appmesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='puesto_votacion',
            field=models.ForeignKey(help_text='Seleccione el puesto de votación correspondiente.', on_delete=django.db.models.deletion.PROTECT, to='AppPuestoVotacion.puestovotacion', verbose_name='Puesto de Votación'),
        ),
    ]
