# Generated by Django 5.2.8 on 2025-12-22 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppMunicipio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corregimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del corregimiento.', max_length=150, unique=True, verbose_name='Nombre del Corregimiento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
                ('municipio', models.ForeignKey(help_text='Seleccione el municipio al que pertenece.', on_delete=django.db.models.deletion.PROTECT, related_name='corregimientos', to='AppMunicipio.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Corregimiento',
                'verbose_name_plural': 'Corregimientos',
            },
        ),
    ]
