# Generated by Django 5.2.8 on 2025-12-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppMunicipio', '0001_initial'),
        ('AppPuestoVotacion', '0001_initial'),
        ('appmesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('LIDER_VOTANTE', 'Líder y Votante'), ('VOTANTE', 'Votante')], default='VOTANTE', max_length=20, verbose_name='Rol')),
                ('nombre', models.CharField(help_text='Ingrese los nombres del votante.', max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(help_text='Ingrese los apellidos del votante.', max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(help_text='Ingrese la cédula sin guiones ni espacios.', max_length=12, unique=True, verbose_name='Cédula')),
                ('direccion_residencia', models.CharField(help_text='Ingrese la dirección de residencia del votante.', max_length=100, verbose_name='Dirección de residencia')),
                ('barrio_residencia', models.CharField(help_text='Barrio de residencia.', max_length=100, verbose_name='Barrio')),
                ('telefono', models.CharField(help_text='Ingrese un número de contacto.', max_length=100, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
                ('lider_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'LIDER_VOTANTE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votantes_asignados', to='appformulario.votante', verbose_name='Líder Responsable')),
                ('mesa', models.ForeignKey(help_text='Seleccione.', on_delete=django.db.models.deletion.PROTECT, to='appmesa.mesa', verbose_name='Mesa de Votación')),
                ('municipio_nacimiento', models.ForeignKey(help_text='Seleccione el municipio de nacimiento', on_delete=django.db.models.deletion.PROTECT, to='AppMunicipio.municipio', verbose_name='Municipio de Nacimiento')),
                ('puesto_votacion', models.ForeignKey(help_text='Seleccione el puesto de votación.', on_delete=django.db.models.deletion.PROTECT, to='AppPuestoVotacion.puestovotacion', verbose_name='Puesto de Votación')),
            ],
            options={
                'verbose_name': 'votante',
                'verbose_name_plural': 'votantes',
                'permissions': [('change_status_votante', 'Puede activar/inactivar votantes')],
            },
        ),
    ]
