# Generated by Django 5.2.8 on 2025-12-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppPuestoVotacion', '0001_initial'),
        ('applider', '0001_initial'),
        ('appmesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese los nombres del votante.', max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(help_text='Ingrese los apellidos del votante.', max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(help_text='Ingrese la cédula sin guiones ni espacios.', max_length=12, unique=True, verbose_name='Cédula')),
                ('direccion_residencia', models.CharField(blank=True, help_text='Ingrese la dirección de residencia del votante.', max_length=100, null=True, verbose_name='Dirección de residencia')),
                ('telefono', models.CharField(help_text='Ingrese un número de contacto.', max_length=100, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
                ('lider', models.ForeignKey(help_text='Seleccione el líder responsable del votante.', on_delete=django.db.models.deletion.PROTECT, to='applider.lider', verbose_name='Líder')),
                ('mesa', models.ForeignKey(help_text='Seleccione.', on_delete=django.db.models.deletion.PROTECT, to='appmesa.mesa', verbose_name='Mesa de Votación')),
                ('puesto_votacion', models.ForeignKey(help_text='Seleccione el puesto de votación.', on_delete=django.db.models.deletion.PROTECT, to='AppPuestoVotacion.puestovotacion', verbose_name='Puesto de Votación')),
            ],
            options={
                'verbose_name': 'votante',
                'verbose_name_plural': 'votantes',
            },
        ),
    ]
