# Generated by Django 5.2.8 on 2025-12-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votante',
            options={'permissions': [('change_status_votante', 'Puede activar/inactivar votantes')], 'verbose_name': 'votante', 'verbose_name_plural': 'votantes'},
        ),
    ]
