# Generated by Django 5.2.8 on 2025-12-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='barrio_residencia',
            field=models.CharField(blank=True, help_text='Barrio de residencia.', max_length=100, null=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='direccion_residencia',
            field=models.CharField(blank=True, help_text='Ingrese la dirección de residencia del votante.', max_length=100, null=True, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ingrese un número de contacto.', max_length=100, null=True, verbose_name='Teléfono'),
        ),
    ]
