# Generated by Django 5.2.8 on 2025-11-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0002_municipio_status_alter_municipio_nombre'),
        ('AppPuestoVotacion', '0003_puestovotacion_status_and_more'),
        ('appformulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='apellido',
            field=models.CharField(help_text='Ingrese los apellidos del votante.', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='cedula',
            field=models.CharField(help_text='Ingrese la cédula sin guiones ni espacios.', max_length=12, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='edad',
            field=models.IntegerField(help_text='Ingrese la edad actual.'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='lider',
            field=models.CharField(help_text='Nombre del líder de equipo.', max_length=100, verbose_name='Líder'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='municipio_nacimiento',
            field=models.ForeignKey(help_text='Seleccione el lugar de nacimiento.', null=True, on_delete=django.db.models.deletion.PROTECT, to='AppMunicipio.municipio', verbose_name='Lugar de nacimiento.'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='nombre',
            field=models.CharField(help_text='Ingrese los nombres del votante.', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='puesto_votacion',
            field=models.ForeignKey(help_text='Seleccione el puesto de votación.', null=True, on_delete=django.db.models.deletion.PROTECT, to='AppPuestoVotacion.puestovotacion', verbose_name='Lugar de Votación'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='telefono',
            field=models.CharField(help_text='Ingrese un número de contacto.', max_length=100, verbose_name='Teléfono'),
        ),
    ]
