# Generated by Django 5.2.8 on 2025-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='direccion_residencia',
            field=models.CharField(blank=True, help_text='Ingrese la dirección de residencia del votante.', max_length=100, null=True, verbose_name='Dirección de residencia'),
        ),
    ]
