# Generated by Django 5.2.8 on 2025-12-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0002_alter_votante_direccion_residencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='puesto_votacion',
        ),
    ]
