# Generated by Django 5.2.8 on 2025-12-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0002_alter_votante_barrio_residencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votante',
            old_name='municipio_nacimiento',
            new_name='municipio_residencia',
        ),
    ]
