# Generated by Django 5.2.8 on 2025-12-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0002_alter_votante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='barrio_residencia',
            field=models.CharField(default=1, help_text='Barrio de residencia.', max_length=100, verbose_name='Barrio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votante',
            name='direccion_residencia',
            field=models.CharField(help_text='Ingrese la dirección de residencia del votante.', max_length=100, verbose_name='Dirección de residencia'),
        ),
    ]
