# Generated by Django 5.2.8 on 2025-12-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0003_rename_municipio_nacimiento_votante_municipio_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='rol',
            field=models.CharField(choices=[('LIDER_VOTANTE', 'Líder'), ('VOTANTE', 'Votante')], default='VOTANTE', max_length=20, verbose_name='Rol'),
        ),
    ]
