# Generated by Django 5.2.8 on 2025-12-22 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcorregimientos', '0001_initial'),
        ('appformulario', '0004_alter_votante_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='corregimiento_residencia',
            field=models.ForeignKey(blank=True, help_text='Seleccione el corregimiento de residencia', null=True, on_delete=django.db.models.deletion.PROTECT, to='appcorregimientos.corregimiento', verbose_name='Corregimiento de Residencia'),
        ),
    ]
