# Generated by Django 5.2.8 on 2025-12-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdepartamento', '0001_initial'),
        ('appformulario', '0005_votante_corregimiento_residencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='departamento_residencia',
            field=models.ForeignKey(blank=True, help_text='Seleccione el departamento de residencia', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdepartamento.departamento', verbose_name='Departamento de residencia'),
        ),
    ]
