# Generated by Django 5.2.8 on 2025-12-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0006_votante_departamento_residencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votante',
            options={'permissions': [('change_status_votante', 'Puede activar/inactivar votantes'), ('export_excel_votante', 'Puede exportar votantes a Excel')], 'verbose_name': 'votante', 'verbose_name_plural': 'votantes'},
        ),
    ]
