# Generated by Django 5.2.8 on 2025-12-28 04:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0003_alter_municipio_nombre'),
        ('AppPuestoVotacion', '0005_alter_puestovotacion_municipio'),
        ('appcorregimientos', '0001_initial'),
        ('appdepartamento', '0001_initial'),
        ('appformulario', '0007_alter_votante_options'),
        ('appmesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVotante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rol', models.CharField(choices=[('LIDER_VOTANTE', 'Líder'), ('VOTANTE', 'Votante')], default='VOTANTE', max_length=20, verbose_name='Rol')),
                ('nombre', models.CharField(help_text='Ingrese los nombres del votante.', max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(help_text='Ingrese los apellidos del votante.', max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(db_index=True, help_text='Ingrese la cédula sin guiones ni espacios.', max_length=12, verbose_name='Cédula')),
                ('direccion_residencia', models.CharField(blank=True, help_text='Ingrese la dirección de residencia del votante.', max_length=100, null=True, verbose_name='Dirección de residencia')),
                ('barrio_residencia', models.CharField(blank=True, help_text='Barrio de residencia.', max_length=100, null=True, verbose_name='Barrio')),
                ('telefono', models.CharField(blank=True, help_text='Ingrese un número de contacto.', max_length=100, null=True, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('corregimiento_residencia', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione el corregimiento de residencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcorregimientos.corregimiento', verbose_name='Corregimiento de Residencia')),
                ('departamento_residencia', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione el departamento de residencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appdepartamento.departamento', verbose_name='Departamento de residencia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lider_asignado', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'rol': 'LIDER_VOTANTE'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appformulario.votante', verbose_name='Líder Responsable')),
                ('mesa', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appmesa.mesa', verbose_name='Mesa de Votación')),
                ('municipio_residencia', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione el municipio de nacimiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppMunicipio.municipio', verbose_name='Municipio de Nacimiento')),
                ('puesto_votacion', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione el puesto de votación.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppPuestoVotacion.puestovotacion', verbose_name='Puesto de Votación')),
            ],
            options={
                'verbose_name': 'historical votante',
                'verbose_name_plural': 'historical votantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
