# Generated by Django 5.2.8 on 2026-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0008_historicalvotante'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvotante',
            name='motivo_inactivacion',
            field=models.TextField(blank=True, help_text='Explique brevemente por qué se inactivó a esta persona.', null=True, verbose_name='Motivo de Inactivación'),
        ),
        migrations.AddField(
            model_name='votante',
            name='motivo_inactivacion',
            field=models.TextField(blank=True, help_text='Explique brevemente por qué se inactivó a esta persona.', null=True, verbose_name='Motivo de Inactivación'),
        ),
    ]
