# Generated by Django 5.2.8 on 2026-01-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0009_historicalvotante_motivo_inactivacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvotante',
            name='rol',
            field=models.CharField(choices=[('VOTANTE', 'Votante'), ('LIDER_EG', 'Líder Equipo Guajira'), ('SUBLIDER', 'Sublíder')], default='VOTANTE', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='rol',
            field=models.CharField(choices=[('VOTANTE', 'Votante'), ('LIDER_EG', 'Líder Equipo Guajira'), ('SUBLIDER', 'Sublíder')], default='VOTANTE', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='LiderEG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_lider_eg', to='appformulario.votante')),
            ],
        ),
        migrations.AddField(
            model_name='historicalvotante',
            name='lider_eg',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appformulario.lidereg'),
        ),
        migrations.AddField(
            model_name='votante',
            name='lider_eg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votantes', to='appformulario.lidereg'),
        ),
        migrations.CreateModel(
            name='SubLider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider_eg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sublideres', to='appformulario.lidereg')),
                ('votante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sublider', to='appformulario.votante')),
            ],
        ),
        migrations.AddField(
            model_name='historicalvotante',
            name='sublider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appformulario.sublider'),
        ),
        migrations.AddField(
            model_name='votante',
            name='sublider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votantes', to='appformulario.sublider'),
        ),
    ]
