# Generated by Django 5.2.8 on 2026-01-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0012_change_lider_votante_to_lider_eg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvotante',
            name='lider_asignado',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='lider_asignado',
        ),
    ]
