# Generated by Django 5.2.8 on 2025-12-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre completo del líder.', max_length=100, verbose_name='Nombre del líder')),
                ('cedula', models.CharField(help_text='Número de identificación del líder.', max_length=20, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto del líder.', max_length=12, null=True, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Líder',
                'verbose_name_plural': 'Líderes',
            },
        ),
    ]
