# Generated by Django 5.2.8 on 2025-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de contacto del líder.', max_length=12, null=True, verbose_name='Teléfono'),
        ),
    ]
