# Generated by Django 5.2.8 on 2025-11-28 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppMunicipio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(help_text='Ingrese el nombre del puesto de votación.', max_length=200, unique=True, verbose_name='Nombre del puesto')),
                ('aplica_direccion', models.BooleanField(default=True, verbose_name='¿El puesto tiene dirección física?')),
                ('direccion', models.CharField(blank=True, help_text='Ingrese la dirección del puesto o marque N/A si no aplica.', max_length=255, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado')),
                ('municipio', models.ForeignKey(help_text='Seleccione la ubicación geográfica del puesto.', on_delete=django.db.models.deletion.PROTECT, to='AppMunicipio.municipio', verbose_name='Municipio o Corregimiento')),
            ],
            options={
                'verbose_name': 'Puesto de Votación',
                'verbose_name_plural': 'Puestos de Votación',
            },
        ),
    ]
