# Generated by Django 5.2.8 on 2025-11-23 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppMunicipio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=200, unique=True, verbose_name='Ingrese el lugar de votación')),
                ('direccion', models.CharField(max_length=255, verbose_name='Ingrese la dirección')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppMunicipio.municipio', verbose_name='Municipio o Corregimiento')),
            ],
            options={
                'verbose_name': 'Puesto de Votación',
                'verbose_name_plural': 'Puestos de Votación',
            },
        ),
    ]
