# Generated by Django 5.2.8 on 2025-11-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPuestoVotacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestovotacion',
            name='aplica_direccion',
            field=models.BooleanField(default=True, verbose_name='¿Aplica dirección?'),
        ),
    ]
