# Generated by Django 5.2.8 on 2025-12-23 02:08

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPuestoVotacion', '0001_initial'),
        ('appcorregimientos', '0001_initial'),
        ('appdepartamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestovotacion',
            name='corregimiento',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.PROTECT, to='appcorregimientos.corregimiento', verbose_name='Corregimiento'),
        ),
        migrations.AddField(
            model_name='puestovotacion',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appdepartamento.departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
    ]
