# Generated by Django 5.2.8 on 2025-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPuestoVotacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestovotacion',
            name='aplica_direccion',
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ingrese la dirección del puesto o marque N/A si no aplica.', max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
