# Generated by Django 5.2.8 on 2025-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPuestoVotacion', '0002_remove_puestovotacion_aplica_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestovotacion',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ingrese la dirección del puesto (opcional)', max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
