# Generated by Django 5.2.8 on 2025-11-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0002_municipio_status_alter_municipio_nombre'),
        ('AppPuestoVotacion', '0002_puestovotacion_aplica_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestovotacion',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado actual (Activo/Inactivo).', max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='aplica_direccion',
            field=models.BooleanField(default=True, verbose_name='¿El puesto tiene dirección física?'),
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ingrese la dirección del puesto o marque N/A si no aplica.', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='municipio',
            field=models.ForeignKey(help_text='Seleccione la ubicación geográfica del puesto.', on_delete=django.db.models.deletion.PROTECT, to='AppMunicipio.municipio', verbose_name='Municipio o Corregimiento'),
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='nombre_lugar',
            field=models.CharField(help_text='Ingrese el nombre del puesto de votación.', max_length=200, unique=True, verbose_name='Nombre del puesto'),
        ),
    ]
