# Generated by Django 5.2.8 on 2025-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPuestoVotacion', '0003_remove_puestovotacion_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestovotacion',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ingrese la dirección del puesto (opcional)', max_length=100, null=True, verbose_name='Dirección'),
        ),
    ]
