# Generated by Django 5.2.8 on 2025-12-23 02:31

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0002_alter_municipio_options'),
        ('AppPuestoVotacion', '0003_alter_puestovotacion_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestovotacion',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='departamento', chained_model_field='departamento', help_text='Seleccione la ubicación geográfica del puesto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='AppMunicipio.municipio', verbose_name='Municipio'),
        ),
    ]
