# Generated by Django 5.2.8 on 2025-12-23 02:35

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMunicipio', '0002_alter_municipio_options'),
        ('AppPuestoVotacion', '0004_alter_puestovotacion_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestovotacion',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento', default=1, help_text='Seleccione la ubicación geográfica del puesto.', on_delete=django.db.models.deletion.PROTECT, to='AppMunicipio.municipio', verbose_name='Municipio'),
            preserve_default=False,
        ),
    ]
